/-
  SimVerilator — Verilator backend for the unified `Sim` typeclass.

  Verilator's native build model is `verilator --cc <design.sv> -o
  obj_dir/V<top>` followed by hand-written C++.  To plug into the
  same `Sim` interface as the JIT backend we wrap that pipeline so
  the resulting shared library exports the **same C ABI** the JIT
  uses (`jit_create / jit_eval_tick / jit_set_input / jit_get_output
  / jit_reset / jit_destroy`).  Because the ABI matches, the
  existing `Sparkle.Core.JIT.JITHandle` opaque + FFI works
  unchanged — we just hand it a Verilator-backed `.so` instead of a
  CppSim-backed one.

  Build pipeline (offline, kicked off lazily by `load`):

  1.  `IO.FS.writeFile <svPath> <verilog>` — written by the user
      *before* calling `load`, e.g. via
      `Sparkle.Backend.Verilog.writeVerilogFile`.
  2.  `verilator --cc --build --top-module <top> -CFLAGS '-O2 -fPIC'
       -LDFLAGS '-shared' --Mdir <objDir> -o <so> <svPath> <tbCpp>`
      where `tbCpp` is the small wrapper this module emits.
  3.  `JIT.load <so>` — the same dlopen path the CppSim backend uses.

  The user-visible interface is one function:

      Verilator.of svPath topModule inputs outputs : IO Simulator

  plus the `Sim` instance.  We reuse the JIT FFI for the runtime
  calls so there is no second set of `extern "C"` bindings to
  maintain.
-/
import Sparkle.Core.JIT
import Sparkle.Core.Sim

namespace Sparkle.Core.Sim.Verilator

open Sparkle.Core.JIT

/-- One input port: name (matches the `.sv` port) and bit-width.
    The width drives the C++ type chosen for the `jit_set_input`
    switch case (`uint8_t`, `uint16_t`, `uint32_t`, or `uint64_t`). -/
structure PortSpec where
  name  : String
  width : Nat
  deriving Repr, Inhabited

/-- Verilator simulator state.  Just a `JITHandle` because the
    Verilator-backed `.so` exposes the JIT C ABI. -/
structure Simulator where
  handle : JITHandle

/-- Pick the smallest unsigned C type that holds `width` bits. -/
private def cTypeFor (width : Nat) : String :=
  if width ≤ 8 then "uint8_t"
  else if width ≤ 16 then "uint16_t"
  else if width ≤ 32 then "uint32_t"
  else "uint64_t"

/-- Emit the C++ testbench / FFI shim that wraps a Verilator
    `V<top>` model behind the JIT C ABI.  The resulting `.cpp`
    is compiled together with the Verilator-generated sources by
    `verilator --build`. -/
private def emitTb (top : String) (inputs outputs : List PortSpec)
    : String :=
  let cls := s!"V{top}"
  -- Compute switch cases for set_input / get_output.
  let setCases :=
    String.intercalate "\n" <|
      (List.range inputs.length).zip inputs |>.map fun (i, p) =>
        s!"        case {i}: m->{p.name} = ({cTypeFor p.width})val; break;"
  let getCases :=
    String.intercalate "\n" <|
      (List.range outputs.length).zip outputs |>.map fun (i, p) =>
        s!"        case {i}: return (uint64_t)m->{p.name};"
  -- Stitch the wrapper.
  "// Auto-generated by Sparkle.Core.Sim.Verilator.\n" ++
  "// Exposes the JIT C ABI on top of a Verilator-built model.\n" ++
  let castM := "static_cast<" ++ cls ++ "*>(ctx)"
  "#include \"" ++ cls ++ ".h\"\n" ++
  "#include <cstdint>\n\n" ++
  "extern \"C\" {\n\n" ++
  "void* jit_create() { auto* m = new " ++ cls ++ "(); return (void*)m; }\n" ++
  "void  jit_destroy(void* ctx) { delete " ++ castM ++ "; }\n\n" ++
  -- Reset: pulse rst high for one cycle, then low.  Matches the
  -- behaviour of the CppSim `reset()` member.
  "void  jit_reset(void* ctx) {\n" ++
  "    auto* m = " ++ castM ++ ";\n" ++
  "    m->rst = 1; m->clk = 0; m->eval();\n" ++
  "    m->clk = 1; m->eval();\n" ++
  "    m->rst = 0; m->clk = 0; m->eval();\n" ++
  "}\n\n" ++
  -- eval / tick / fused.
  "void jit_eval(void* ctx) { " ++ castM ++ "->eval(); }\n" ++
  "void jit_tick(void* ctx) {\n" ++
  "    auto* m = " ++ castM ++ ";\n" ++
  "    m->clk = 1; m->eval();\n" ++
  "    m->clk = 0; m->eval();\n" ++
  "}\n\n" ++
  "void jit_eval_tick(void* ctx) {\n" ++
  "    auto* m = " ++ castM ++ ";\n" ++
  "    m->clk = 1; m->eval();\n" ++
  "    m->clk = 0; m->eval();\n" ++
  "}\n\n" ++
  "void jit_set_input(void* ctx, uint32_t idx, uint64_t val) {\n" ++
  "    auto* m = " ++ castM ++ ";\n" ++
  "    switch (idx) {\n" ++
  setCases ++ "\n" ++
  "        default: break;\n    }\n}\n\n" ++
  "uint64_t jit_get_output(void* ctx, uint32_t idx) {\n" ++
  "    auto* m = " ++ castM ++ ";\n" ++
  "    switch (idx) {\n" ++
  getCases ++ "\n" ++
  "        default: return 0;\n    }\n}\n\n" ++
  "} // extern \"C\"\n"

/-- Build a Verilator-backed `.so` from a Sparkle-generated `.sv`,
    then load it via the existing JIT FFI.

    - `svPath` — path to a `.sv` written by, e.g.,
      `Sparkle.Backend.Verilog.writeVerilogFile`.
    - `top`    — top-module name (matches what's in the `.sv`).
    - `inputs` / `outputs` — port lists *excluding* `clk` / `rst`
      (matching the JIT's `jit_set_input` / `jit_get_output`
      indexing).
    - `objDir` — temp directory for Verilator artefacts.

    Returns a `Simulator` whose `handle` is opened against the
    just-built `.so`. -/
def of (svPath top : String) (inputs outputs : List PortSpec)
    (objDir : String := "/tmp/sparkle_verilator") : IO Simulator := do
  IO.FS.createDirAll objDir
  let tbPath := s!"{objDir}/sparkle_verilator_tb.cpp"
  IO.FS.writeFile tbPath (emitTb top inputs outputs)
  let soPath := s!"{objDir}/V{top}.so"
  let r ← IO.Process.output {
    cmd := "verilator"
    args := #[
      "--cc", "--build", "-j", "0",
      "--top-module", top,
      "-CFLAGS", "-O2 -fPIC",
      "-LDFLAGS", s!"-shared -o {soPath}",
      "--Mdir", objDir,
      "-Wno-WIDTHEXPAND", "-Wno-WIDTHTRUNC",
      "-Wno-UNUSEDSIGNAL", "-Wno-CASEINCOMPLETE",
      svPath, tbPath ]
    stdin := .null
  }
  if r.exitCode != 0 then
    throw (IO.userError s!"verilator build failed (exit {r.exitCode}):\n{r.stderr}")
  let handle ← JIT.load soPath
  pure { handle := handle }

instance : Sparkle.Core.Sim.Sim Simulator
    (List (UInt32 × UInt64))    -- raw (port-index, value) drives
    (UInt32 → IO UInt64)        -- a getter you call per cycle
    where
  reset sim := JIT.reset sim.handle
  step sim drives := do
    for (idx, val) in drives do
      JIT.setInput sim.handle idx val
    JIT.evalTick sim.handle
  read sim := pure (fun idx => JIT.getOutput sim.handle idx)
  destroy sim := JIT.destroy sim.handle

end Sparkle.Core.Sim.Verilator
