/-
  Example: a parametric RC ladder (metaprogramming)

  An N-stage RC ladder, generated by an ordinary Lean loop. In Verilog-A this
  needs a `generate` block with string-indexed node names (`n[i]`, `n[i+1]`) —
  easy to get off-by-one or mis-wire, and not checkable until elaboration. Here
  the stage count is just a `Nat` argument, the nodes are real binders threaded
  through the loop, and the whole thing is an ordinary, type-checked function.

  This is also where the monadic builder earns its keep: programmatic assembly of
  an unbounded number of nets/devices reads naturally as a `for` loop.
-/

import Sparkle.Analog

open Sparkle.Analog

namespace Examples.Analog.Ladder

/-- An `n`-stage RC ladder driven by a 5 V source: each stage is a series
resistor followed by a shunt capacitor to ground. The output is the last node. -/
def ladder (n : Nat) (R : Ohm) (C : Farad) : Circuit := runCircuit do
  let src ← net
  place (vsourceDC (volts 5.0)) src ground
  let mut prev := src
  for _ in [0:n] do
    let node ← net
    place (resistor R) prev node
    place (capacitor C) node ground
    prev := node

def demo : IO Unit := do
  IO.println "Parametric RC ladder (one Lean loop, no generate blocks):"
  for stages in [1, 3, 5] do
    let c := ladder stages (ohms 1e3) (farads 1e-6)
    -- At DC every node settles to the source (caps block DC, no steady current).
    let vOut := (c.transient 1e-5 4000).finalNet c stages
    IO.println s!"  {stages} stages → {c.netCount} nets, last node at 40ms = {vOut} V"
  IO.println ""

end Examples.Analog.Ladder
